# Generated by Django 5.2.6 on 2025-09-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
